org.gradle.jvmargs=-Xmx4608m -XX:MaxMetaspaceSize=768m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.java.home=C:/Program Files/JetBrains/IntelliJ IDEA 2024.1.4/jbr
org.gradle.workers.max=1
org.gradle.parallel=false
kotlin.daemon.jvmargs=-Xmx1024m
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.suppressUnsupportedCompileSdk=36
android.dexingUseForkJoinPool=false
