package com.nocap.app.presentation.memory

import android.net.Uri
import android.widget.Toast
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowForward
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import com.nocap.app.core.database.dao.ReviewItemWithDetails
import com.nocap.app.core.designsystem.AppIcons
import com.nocap.app.core.localization.Text
import com.nocap.app.core.localization.localize
import com.nocap.app.data.billing.EntitlementPolicy
import com.nocap.app.data.billing.Feature
import com.nocap.app.domain.model.BookmarkWithBook
import com.nocap.app.domain.model.HighlightWithBook
import com.nocap.app.domain.repository.AutoGenResult
import com.nocap.app.domain.review.MemoryState
import com.nocap.app.domain.review.ReviewScheduler
import kotlinx.coroutines.launch
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ReadingMemoryScreen(
    onNavigateToReader: (bookId: String, locatorJson: String?) -> Unit,
    onNavigateToReviewQueue: (mode: String?) -> Unit,
    onNavigateToSearch: () -> Unit,
    onNavigateToGlobalAnnotations: () -> Unit,
    onNavigateToStats: () -> Unit,
    viewModel: ReadingMemoryViewModel = viewModel(
        factory = ReadingMemoryViewModel.provideFactory(LocalContext.current)
    )
) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()

    val entitlementRepo = remember { com.nocap.app.data.billing.EntitlementRepository.get(context) }
    val entitlementState by entitlementRepo.state.collectAsStateWithLifecycle()
    val hasAdvancedMemory = remember(entitlementState) {
        EntitlementPolicy.allows(
            Feature.ADVANCED_READING_MEMORY,
            entitlementState.entitlement,
            entitlementRepo.activeUser()
        )
    }
    val hasKnowledgeExport = remember(entitlementState) {
        EntitlementPolicy.allows(
            Feature.KNOWLEDGE_EXPORT,
            entitlementState.entitlement,
            entitlementRepo.activeUser()
        )
    }

    var isExporting by remember { mutableStateOf(false) }
    var showExportDialog by remember { mutableStateOf(false) }
    var showAutoGenerateDialog by remember { mutableStateOf(false) }
    var showProRequiredDialog by remember { mutableStateOf(false) }
    var proRequiredMessage by remember { mutableStateOf("") }

    // Export dialog configurations
    var selectedScope by remember { mutableStateOf("ALL") } // "ALL", "BOOK", "TOPIC"
    var selectedBookId by remember { mutableStateOf<String?>(null) }
    var selectedTopicColor by remember { mutableStateOf("ALL") } // "ALL", "YELLOW", "GREEN", "BLUE", "PINK"
    var selectedFormat by remember { mutableStateOf("MARKDOWN") } // "MARKDOWN", "PDF", "ANKI"

    val markdownLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.CreateDocument("text/markdown")
    ) { uri: Uri? ->
        if (uri != null) {
            scope.launch {
                isExporting = true
                val success = runCatching {
                    context.contentResolver.openOutputStream(uri)?.use { output ->
                        viewModel.exportMarkdown(
                            output,
                            bookId = if (selectedScope == "BOOK") selectedBookId else null,
                            topicColor = if (selectedScope == "TOPIC") selectedTopicColor else null
                        )
                    } ?: false
                }.getOrDefault(false)
                isExporting = false
                Toast.makeText(
                    context,
                    com.nocap.app.core.localization.AppLanguageManager.translate(
                        context,
                        if (success) "Đã xuất tệp Markdown thành công!" else "Lỗi khi xuất tệp Markdown"
                    ),
                    Toast.LENGTH_SHORT
                ).show()
            }
        }
    }

    val pdfLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.CreateDocument("application/pdf")
    ) { uri: Uri? ->
        if (uri != null) {
            scope.launch {
                isExporting = true
                val success = runCatching {
                    context.contentResolver.openOutputStream(uri)?.use { output ->
                        viewModel.exportPdf(
                            output,
                            bookId = if (selectedScope == "BOOK") selectedBookId else null,
                            topicColor = if (selectedScope == "TOPIC") selectedTopicColor else null
                        )
                    } ?: false
                }.getOrDefault(false)
                isExporting = false
                Toast.makeText(
                    context,
                    com.nocap.app.core.localization.AppLanguageManager.translate(
                        context,
                        if (success) "Đã xuất tài liệu PDF thành công!" else "Lỗi khi xuất tài liệu PDF"
                    ),
                    Toast.LENGTH_SHORT
                ).show()
            }
        }
    }

    val ankiLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.CreateDocument("text/tab-separated-values")
    ) { uri: Uri? ->
        if (uri != null) {
            scope.launch {
                isExporting = true
                val success = runCatching {
                    context.contentResolver.openOutputStream(uri)?.use { output ->
                        viewModel.exportAnki(
                            output,
                            bookId = if (selectedScope == "BOOK") selectedBookId else null,
                            topicColor = if (selectedScope == "TOPIC") selectedTopicColor else null
                        )
                    } ?: false
                }.getOrDefault(false)
                isExporting = false
                Toast.makeText(
                    context,
                    com.nocap.app.core.localization.AppLanguageManager.translate(
                        context,
                        if (success) "Đã xuất bộ thẻ Flashcard Anki thành công!" else "Lỗi khi xuất bộ thẻ Anki"
                    ),
                    Toast.LENGTH_SHORT
                ).show()
            }
        }
    }

    // Auto-generate Review Items Dialog
    if (showAutoGenerateDialog) {
        var onlyNotes by remember { mutableStateOf(false) }
        var isGenerating by remember { mutableStateOf(false) }

        AlertDialog(
            onDismissRequest = { if (!isGenerating) showAutoGenerateDialog = false },
            title = { Text("Tự động tạo danh sách ôn tập") },
            text = {
                Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                    Text(
                        text = "Hệ thống sẽ quét các điểm nhấn và ghi chú của bạn để lên lịch ôn tập theo phương pháp lặp lại ngắt quãng (Spaced Repetition).",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        modifier = Modifier
                            .fillMaxWidth()
                            .clickable { onlyNotes = !onlyNotes }
                            .padding(vertical = 4.dp)
                    ) {
                        Checkbox(
                            checked = onlyNotes,
                            onCheckedChange = { onlyNotes = it }
                        )
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(
                            text = "Chỉ tạo thẻ từ đoạn trích có ghi chú",
                            style = MaterialTheme.typography.bodyMedium
                        )
                    }
                }
            },
            confirmButton = {
                Button(
                    onClick = {
                        scope.launch {
                            isGenerating = true
                            val result = viewModel.autoGenerateReviewDetailed(onlyNotes)
                            isGenerating = false
                            showAutoGenerateDialog = false
                            result.onSuccess { autoGen ->
                                val msg = when (autoGen) {
                                    is AutoGenResult.Added -> "Đã thêm ${autoGen.count} thẻ mới vào danh sách ôn tập!"
                                    is AutoGenResult.NoHighlightsAtAll -> "Chưa có điểm trích dẫn nào trong sách để tạo thẻ."
                                    is AutoGenResult.NoHighlightsWithNotes -> "Không có điểm trích dẫn nào có ghi chú để tạo thẻ."
                                    is AutoGenResult.AllAlreadyInReview -> "Tất cả ${autoGen.total} điểm trích dẫn đã có trong danh sách ôn tập."
                                }
                                Toast.makeText(
                                    context,
                                    com.nocap.app.core.localization.AppLanguageManager.translate(context, msg),
                                    Toast.LENGTH_SHORT
                                ).show()
                            }.onFailure {
                                val errPrefix = com.nocap.app.core.localization.AppLanguageManager.translate(context, "Không thể tạo danh sách ôn tập")
                                Toast.makeText(context, "$errPrefix: ${it.localizedMessage}", Toast.LENGTH_SHORT).show()
                            }
                        }
                    },
                    enabled = !isGenerating
                ) {
                    if (isGenerating) {
                        CircularProgressIndicator(modifier = Modifier.size(16.dp), strokeWidth = 2.dp)
                        Spacer(modifier = Modifier.width(8.dp))
                    }
                    Text("Tạo danh sách")
                }
            },
            dismissButton = {
                TextButton(
                    onClick = { showAutoGenerateDialog = false },
                    enabled = !isGenerating
                ) {
                    Text("Hủy")
                }
            }
        )
    }

    // Export Knowledge Dialog
    if (showExportDialog) {
        var bookDropdownExpanded by remember { mutableStateOf(false) }

        AlertDialog(
            onDismissRequest = { showExportDialog = false },
            title = { Text("Xuất và sử dụng tri thức") },
            text = {
                Column(
                    modifier = Modifier.fillMaxWidth(),
                    verticalArrangement = Arrangement.spacedBy(12.dp)
                ) {
                    Text("Phạm vi xuất", style = MaterialTheme.typography.labelMedium, fontWeight = FontWeight.Bold)

                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        FilterChip(
                            selected = selectedScope == "ALL",
                            onClick = { selectedScope = "ALL" },
                            label = { Text("Tất cả", fontSize = 12.sp) }
                        )
                        FilterChip(
                            selected = selectedScope == "BOOK",
                            onClick = {
                                selectedScope = "BOOK"
                                if (selectedBookId == null) {
                                    selectedBookId = uiState.allBooks.firstOrNull()?.id
                                }
                            },
                            label = { Text("Theo sách", fontSize = 12.sp) }
                        )
                        FilterChip(
                            selected = selectedScope == "TOPIC",
                            onClick = { selectedScope = "TOPIC" },
                            label = { Text("Theo màu", fontSize = 12.sp) }
                        )
                    }

                    if (selectedScope == "BOOK" && uiState.allBooks.isNotEmpty()) {
                        Box {
                            val selectedBookTitle = uiState.allBooks.firstOrNull { it.id == selectedBookId }?.let {
                                it.userTitleOverride ?: it.title
                            } ?: "Chọn sách..."

                            OutlinedButton(
                                onClick = { bookDropdownExpanded = true },
                                modifier = Modifier.fillMaxWidth()
                            ) {
                                Text(selectedBookTitle, maxLines = 1, overflow = TextOverflow.Ellipsis)
                            }
                            DropdownMenu(
                                expanded = bookDropdownExpanded,
                                onDismissRequest = { bookDropdownExpanded = false }
                            ) {
                                uiState.allBooks.forEach { book ->
                                    DropdownMenuItem(
                                        text = { Text(book.userTitleOverride ?: book.title) },
                                        onClick = {
                                            selectedBookId = book.id
                                            bookDropdownExpanded = false
                                        }
                                    )
                                }
                            }
                        }
                    }

                    if (selectedScope == "TOPIC") {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.spacedBy(6.dp)
                        ) {
                            listOf("ALL" to "Tất cả", "YELLOW" to "Vàng", "GREEN" to "Xanh lá", "BLUE" to "Xanh dương", "PINK" to "Hồng").forEach { (colorKey, colorLabel) ->
                                FilterChip(
                                    selected = selectedTopicColor == colorKey,
                                    onClick = { selectedTopicColor = colorKey },
                                    label = { Text(colorLabel, fontSize = 11.sp) }
                                )
                            }
                        }
                    }

                    HorizontalDivider()

                    Text("Định dạng xuất", style = MaterialTheme.typography.labelMedium, fontWeight = FontWeight.Bold)

                    Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
                        Surface(
                            shape = RoundedCornerShape(8.dp),
                            color = if (selectedFormat == "MARKDOWN") MaterialTheme.colorScheme.primaryContainer else MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f),
                            modifier = Modifier
                                .fillMaxWidth()
                                .clickable { selectedFormat = "MARKDOWN" }
                        ) {
                            Row(
                                modifier = Modifier.padding(10.dp),
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.SpaceBetween
                            ) {
                                Column {
                                    Text("Markdown (.md)", fontWeight = FontWeight.SemiBold, style = MaterialTheme.typography.bodyMedium)
                                    Text("Định dạng chuẩn, tương thích Obsidian/Notion", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                                }
                                Surface(shape = RoundedCornerShape(4.dp), color = MaterialTheme.colorScheme.surfaceContainerHigh) {
                                    Text("Miễn phí", style = MaterialTheme.typography.labelSmall, modifier = Modifier.padding(horizontal = 6.dp, vertical = 2.dp))
                                }
                            }
                        }

                        Surface(
                            shape = RoundedCornerShape(8.dp),
                            color = if (selectedFormat == "PDF") MaterialTheme.colorScheme.primaryContainer else MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f),
                            modifier = Modifier
                                .fillMaxWidth()
                                .clickable { selectedFormat = "PDF" }
                        ) {
                            Row(
                                modifier = Modifier.padding(10.dp),
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.SpaceBetween
                            ) {
                                Column {
                                    Text("Tài liệu PDF (.pdf)", fontWeight = FontWeight.SemiBold, style = MaterialTheme.typography.bodyMedium)
                                    Text("Trang A4 hoàn chỉnh, sẵn sàng in hoặc lưu trữ", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                                }
                                Surface(shape = RoundedCornerShape(4.dp), color = MaterialTheme.colorScheme.primary) {
                                    Text("PRO", style = MaterialTheme.typography.labelSmall, color = Color.White, modifier = Modifier.padding(horizontal = 6.dp, vertical = 2.dp))
                                }
                            }
                        }

                        Surface(
                            shape = RoundedCornerShape(8.dp),
                            color = if (selectedFormat == "ANKI") MaterialTheme.colorScheme.primaryContainer else MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f),
                            modifier = Modifier
                                .fillMaxWidth()
                                .clickable { selectedFormat = "ANKI" }
                        ) {
                            Row(
                                modifier = Modifier.padding(10.dp),
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.SpaceBetween
                            ) {
                                Column {
                                    Text("Bộ thẻ Anki / Flashcard (.tsv)", fontWeight = FontWeight.SemiBold, style = MaterialTheme.typography.bodyMedium)
                                    Text("Nhập vào Anki, Quizlet để học ôn bên ngoài", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                                }
                                Surface(shape = RoundedCornerShape(4.dp), color = MaterialTheme.colorScheme.primary) {
                                    Text("PRO", style = MaterialTheme.typography.labelSmall, color = Color.White, modifier = Modifier.padding(horizontal = 6.dp, vertical = 2.dp))
                                }
                            }
                        }
                    }
                }
            },
            confirmButton = {
                Button(
                    onClick = {
                        if ((selectedFormat == "PDF" || selectedFormat == "ANKI") && !hasKnowledgeExport) {
                            proRequiredMessage = "Xuất tài liệu PDF và bộ thẻ Flashcard Anki là tính năng dành riêng cho gói Pro."
                            showProRequiredDialog = true
                            return@Button
                        }
                        showExportDialog = false
                        val timestamp = SimpleDateFormat("yyyyMMdd_HHmm", Locale.getDefault()).format(Date())
                        when (selectedFormat) {
                            "PDF" -> pdfLauncher.launch("NoCap_Knowledge_$timestamp.pdf")
                            "ANKI" -> ankiLauncher.launch("NoCap_Flashcards_$timestamp.tsv")
                            else -> markdownLauncher.launch("NoCap_Knowledge_$timestamp.md")
                        }
                    }
                ) {
                    Text("Tiến hành xuất")
                }
            },
            dismissButton = {
                TextButton(onClick = { showExportDialog = false }) {
                    Text("Đóng")
                }
            }
        )
    }

    if (showProRequiredDialog) {
        AlertDialog(
            onDismissRequest = { showProRequiredDialog = false },
            title = { Text("Tính năng Pro") },
            text = {
                Text(proRequiredMessage)
            },
            confirmButton = {
                Button(onClick = {
                    showProRequiredDialog = false
                    // Stay on current or let user open settings
                }) {
                    Text("Đã hiểu")
                }
            }
        )
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Text(
                        text = "Ghi nhớ",
                        style = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.Bold)
                    )
                },
                actions = {
                    IconButton(onClick = onNavigateToSearch) {
                        Icon(Icons.Default.Search, contentDescription = localize("Tìm kiếm tri thức"))
                    }
                    IconButton(onClick = onNavigateToStats) {
                        Icon(Icons.Default.Info, contentDescription = localize("Thống kê đọc"))
                    }
                    IconButton(
                        onClick = { showExportDialog = true },
                        enabled = !isExporting
                    ) {
                        if (isExporting) {
                            CircularProgressIndicator(modifier = Modifier.size(20.dp), strokeWidth = 2.dp)
                        } else {
                            Icon(Icons.Default.Share, contentDescription = localize("Xuất tri thức"))
                        }
                    }
                }
            )
        }
    ) { innerPadding ->
        if (uiState.isLoading) {
            Box(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(innerPadding),
                contentAlignment = Alignment.Center
            ) {
                CircularProgressIndicator()
            }
        } else {
            LazyColumn(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(innerPadding)
                    .padding(horizontal = 16.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                // 1. Knowledge Search Entry
                item {
                    Surface(
                        modifier = Modifier
                            .fillMaxWidth()
                            .clickable(onClick = onNavigateToSearch),
                        shape = RoundedCornerShape(12.dp),
                        color = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f),
                        border = androidx.compose.foundation.BorderStroke(
                            1.dp,
                            MaterialTheme.colorScheme.outlineVariant.copy(alpha = 0.5f)
                        )
                    ) {
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(horizontal = 16.dp, vertical = 14.dp),
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(12.dp)
                        ) {
                            Icon(
                                Icons.Default.Search,
                                contentDescription = null,
                                tint = MaterialTheme.colorScheme.primary
                            )
                            Text(
                                text = "Tìm kiếm tri thức trong toàn bộ thư viện...",
                                style = MaterialTheme.typography.bodyMedium,
                                color = MaterialTheme.colorScheme.onSurfaceVariant,
                                modifier = Modifier.weight(1f)
                            )
                        }
                    }
                }

                // 2. Memory State Stats: Theo dõi nội dung đã nhớ, đang học và cần ôn lại
                item {
                    Card(
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(16.dp),
                        colors = CardDefaults.cardColors(
                            containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f)
                        )
                    ) {
                        Column(modifier = Modifier.padding(14.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
                            Text(
                                text = "Tiến trình ghi nhớ",
                                style = MaterialTheme.typography.titleSmall,
                                fontWeight = FontWeight.Bold
                            )

                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.spacedBy(8.dp)
                            ) {
                                // Due / Cần ôn lại
                                Card(
                                    onClick = {
                                        viewModel.setFilter(if (uiState.selectedFilter == MemoryFilter.DUE) MemoryFilter.ALL else MemoryFilter.DUE)
                                    },
                                    modifier = Modifier.weight(1f),
                                    shape = RoundedCornerShape(12.dp),
                                    colors = CardDefaults.cardColors(
                                        containerColor = if (uiState.selectedFilter == MemoryFilter.DUE)
                                            MaterialTheme.colorScheme.errorContainer
                                        else
                                            MaterialTheme.colorScheme.errorContainer.copy(alpha = 0.45f)
                                    ),
                                    border = if (uiState.selectedFilter == MemoryFilter.DUE)
                                        androidx.compose.foundation.BorderStroke(2.dp, MaterialTheme.colorScheme.error)
                                    else null
                                ) {
                                    Column(
                                        modifier = Modifier.padding(10.dp),
                                        horizontalAlignment = Alignment.CenterHorizontally
                                    ) {
                                        Text(
                                            text = "${uiState.reviewStats.dueCount}",
                                            style = MaterialTheme.typography.titleMedium,
                                            fontWeight = FontWeight.Bold,
                                            color = MaterialTheme.colorScheme.error
                                        )
                                        Text(
                                            text = "Cần ôn lại",
                                            style = MaterialTheme.typography.labelSmall,
                                            color = MaterialTheme.colorScheme.onErrorContainer
                                        )
                                    }
                                }

                                // Learning / Đang học
                                Card(
                                    onClick = {
                                        viewModel.setFilter(if (uiState.selectedFilter == MemoryFilter.LEARNING) MemoryFilter.ALL else MemoryFilter.LEARNING)
                                    },
                                    modifier = Modifier.weight(1f),
                                    shape = RoundedCornerShape(12.dp),
                                    colors = CardDefaults.cardColors(
                                        containerColor = if (uiState.selectedFilter == MemoryFilter.LEARNING)
                                            MaterialTheme.colorScheme.primaryContainer
                                        else
                                            MaterialTheme.colorScheme.primaryContainer.copy(alpha = 0.45f)
                                    ),
                                    border = if (uiState.selectedFilter == MemoryFilter.LEARNING)
                                        androidx.compose.foundation.BorderStroke(2.dp, MaterialTheme.colorScheme.primary)
                                    else null
                                ) {
                                    Column(
                                        modifier = Modifier.padding(10.dp),
                                        horizontalAlignment = Alignment.CenterHorizontally
                                    ) {
                                        Text(
                                            text = "${uiState.reviewStats.learningCount}",
                                            style = MaterialTheme.typography.titleMedium,
                                            fontWeight = FontWeight.Bold,
                                            color = MaterialTheme.colorScheme.primary
                                        )
                                        Text(
                                            text = "Đang học",
                                            style = MaterialTheme.typography.labelSmall,
                                            color = MaterialTheme.colorScheme.onPrimaryContainer
                                        )
                                    }
                                }

                                // Mastered / Đã nhớ
                                Card(
                                    onClick = {
                                        viewModel.setFilter(if (uiState.selectedFilter == MemoryFilter.MASTERED) MemoryFilter.ALL else MemoryFilter.MASTERED)
                                    },
                                    modifier = Modifier.weight(1f),
                                    shape = RoundedCornerShape(12.dp),
                                    colors = CardDefaults.cardColors(
                                        containerColor = if (uiState.selectedFilter == MemoryFilter.MASTERED)
                                            MaterialTheme.colorScheme.secondaryContainer
                                        else
                                            MaterialTheme.colorScheme.secondaryContainer.copy(alpha = 0.45f)
                                    ),
                                    border = if (uiState.selectedFilter == MemoryFilter.MASTERED)
                                        androidx.compose.foundation.BorderStroke(2.dp, MaterialTheme.colorScheme.secondary)
                                    else null
                                ) {
                                    Column(
                                        modifier = Modifier.padding(10.dp),
                                        horizontalAlignment = Alignment.CenterHorizontally
                                    ) {
                                        Text(
                                            text = "${uiState.reviewStats.masteredCount}",
                                            style = MaterialTheme.typography.titleMedium,
                                            fontWeight = FontWeight.Bold,
                                            color = MaterialTheme.colorScheme.secondary
                                        )
                                        Text(
                                            text = "Đã nhớ",
                                            style = MaterialTheme.typography.labelSmall,
                                            color = MaterialTheme.colorScheme.onSecondaryContainer
                                        )
                                    }
                                }
                            }
                        }
                    }
                }

                // 3. Due Today Review Card & Quick Session Buttons
                item {
                    Card(
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(16.dp),
                        colors = CardDefaults.cardColors(
                            containerColor = if (uiState.dueTodayCount > 0)
                                MaterialTheme.colorScheme.tertiaryContainer
                            else
                                MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.6f)
                        )
                    ) {
                        Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
                            Row(
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.spacedBy(12.dp)
                            ) {
                                Box(
                                    modifier = Modifier
                                        .size(44.dp)
                                        .background(
                                            if (uiState.dueTodayCount > 0) MaterialTheme.colorScheme.tertiary else MaterialTheme.colorScheme.outline.copy(alpha = 0.3f),
                                            CircleShape
                                        ),
                                    contentAlignment = Alignment.Center
                                ) {
                                    Icon(
                                        if (uiState.dueTodayCount > 0) AppIcons.Book else Icons.Default.Check,
                                        contentDescription = null,
                                        tint = Color.White
                                    )
                                }
                                Column(modifier = Modifier.weight(1f)) {
                                    Text(
                                        text = "Ôn tập hàng ngày",
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold
                                    )
                                    Text(
                                        text = if (uiState.dueTodayCount > 0)
                                            "${uiState.dueTodayCount} nội dung cần ôn tập hôm nay"
                                        else if (uiState.reviewStats.totalCount > 0)
                                            "Hôm nay không có thẻ đến hạn. Bạn có thể ôn sớm!"
                                        else
                                            "Chưa có mục ôn tập nào trong hệ thống.",
                                        style = MaterialTheme.typography.bodyMedium,
                                        color = MaterialTheme.colorScheme.onSurfaceVariant
                                    )
                                }
                            }

                            if (uiState.dueTodayCount > 0) {
                                Button(
                                    onClick = { onNavigateToReviewQueue(null) },
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .heightIn(min = 48.dp),
                                    colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.tertiary)
                                ) {
                                    Text("Bắt đầu ôn tập (${uiState.dueTodayCount})")
                                }

                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                                ) {
                                    OutlinedButton(
                                        onClick = {
                                            if (hasAdvancedMemory) onNavigateToReviewQueue("QUICK_5")
                                            else {
                                                proRequiredMessage = "Phiên ôn nhanh và tự động tạo danh sách ôn tập là tính năng dành riêng cho gói Pro."
                                                showProRequiredDialog = true
                                            }
                                        },
                                        modifier = Modifier.weight(1f).heightIn(min = 44.dp),
                                        shape = RoundedCornerShape(10.dp)
                                    ) {
                                        Text("Ôn nhanh 5p", fontSize = 12.sp)
                                    }

                                    OutlinedButton(
                                        onClick = {
                                            if (hasAdvancedMemory) onNavigateToReviewQueue("QUICK_10")
                                            else {
                                                proRequiredMessage = "Phiên ôn nhanh và tự động tạo danh sách ôn tập là tính năng dành riêng cho gói Pro."
                                                showProRequiredDialog = true
                                            }
                                        },
                                        modifier = Modifier.weight(1f).heightIn(min = 44.dp),
                                        shape = RoundedCornerShape(10.dp)
                                    ) {
                                        Text("Ôn nhanh 10p", fontSize = 12.sp)
                                    }
                                }
                            } else if (uiState.reviewStats.totalCount > 0) {
                                Button(
                                    onClick = { onNavigateToReviewQueue("ALL") },
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .heightIn(min = 48.dp),
                                    colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.primary)
                                ) {
                                    Icon(Icons.Default.PlayArrow, contentDescription = null, modifier = Modifier.size(18.dp))
                                    Spacer(modifier = Modifier.width(8.dp))
                                    Text("Ôn tập tất cả thẻ (${uiState.reviewStats.totalCount})")
                                }
                            }

                            OutlinedButton(
                                onClick = {
                                    if (hasAdvancedMemory) showAutoGenerateDialog = true
                                    else {
                                        proRequiredMessage = "Phiên ôn nhanh và tự động tạo danh sách ôn tập là tính năng dành riêng cho gói Pro."
                                        showProRequiredDialog = true
                                    }
                                },
                                modifier = Modifier.fillMaxWidth().heightIn(min = 44.dp),
                                shape = RoundedCornerShape(10.dp)
                            ) {
                                Icon(Icons.Default.Refresh, contentDescription = null, modifier = Modifier.size(16.dp))
                                Spacer(modifier = Modifier.width(8.dp))
                                Text("Tự động tạo danh sách ôn tập", fontSize = 12.sp)
                            }
                        }
                    }
                }

                // 3b. Danh sách thẻ ôn tập Section
                item {
                    Column(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(top = 10.dp),
                        verticalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(
                                text = "Danh sách thẻ ôn tập",
                                style = MaterialTheme.typography.titleMedium,
                                fontWeight = FontWeight.Bold
                            )
                            Text(
                                text = "${uiState.filteredReviewItems.size} / ${uiState.reviewStats.totalCount} thẻ",
                                style = MaterialTheme.typography.bodySmall,
                                color = MaterialTheme.colorScheme.onSurfaceVariant
                            )
                        }

                        // Filter chips row
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .horizontalScroll(rememberScrollState()),
                            horizontalArrangement = Arrangement.spacedBy(8.dp)
                        ) {
                            FilterChip(
                                selected = uiState.selectedFilter == MemoryFilter.ALL,
                                onClick = { viewModel.setFilter(MemoryFilter.ALL) },
                                label = { Text("Tất cả (${uiState.reviewStats.totalCount})") }
                            )
                            FilterChip(
                                selected = uiState.selectedFilter == MemoryFilter.DUE,
                                onClick = { viewModel.setFilter(MemoryFilter.DUE) },
                                label = { Text("Cần ôn lại (${uiState.reviewStats.dueCount})") }
                            )
                            FilterChip(
                                selected = uiState.selectedFilter == MemoryFilter.LEARNING,
                                onClick = { viewModel.setFilter(MemoryFilter.LEARNING) },
                                label = { Text("Đang học (${uiState.reviewStats.learningCount})") }
                            )
                            FilterChip(
                                selected = uiState.selectedFilter == MemoryFilter.MASTERED,
                                onClick = { viewModel.setFilter(MemoryFilter.MASTERED) },
                                label = { Text("Đã nhớ (${uiState.reviewStats.masteredCount})") }
                            )
                        }
                    }
                }

                if (uiState.filteredReviewItems.isEmpty()) {
                    item {
                        Card(
                            modifier = Modifier.fillMaxWidth(),
                            shape = RoundedCornerShape(12.dp),
                            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.35f))
                        ) {
                            Column(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(20.dp),
                                horizontalAlignment = Alignment.CenterHorizontally,
                                verticalArrangement = Arrangement.spacedBy(6.dp)
                            ) {
                                Icon(
                                    Icons.Default.Info,
                                    contentDescription = null,
                                    tint = MaterialTheme.colorScheme.outline,
                                    modifier = Modifier.size(28.dp)
                                )
                                Text(
                                    text = if (uiState.reviewStats.totalCount == 0)
                                        "Chưa có thẻ ôn tập nào. Hãy bấm 'Tự động tạo danh sách ôn tập' để hệ thống quét các trích dẫn của bạn."
                                    else
                                        "Không có thẻ nào ở trạng thái này.",
                                    style = MaterialTheme.typography.bodyMedium,
                                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                                    textAlign = androidx.compose.ui.text.style.TextAlign.Center
                                )
                            }
                        }
                    }
                } else {
                    items(uiState.filteredReviewItems, key = { it.reviewItem.id }) { itemWithDetails ->
                        ReviewItemCard(
                            itemWithDetails = itemWithDetails,
                            onMarkAsMastered = { viewModel.markItemAsMastered(it) },
                            onRemoveFromReview = { viewModel.removeFromReview(it) },
                            onOpenBook = { bookId, locatorJson ->
                                onNavigateToReader(bookId, locatorJson)
                            }
                        )
                    }
                }

                // 4. Recent Notes & Highlights Section Header
                item {
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(top = 8.dp),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text(
                            text = "Ghi chú & Đoạn trích gần đây",
                            style = MaterialTheme.typography.titleMedium,
                            fontWeight = FontWeight.Bold
                        )
                        TextButton(onClick = onNavigateToGlobalAnnotations) {
                            Text("Xem tất cả")
                        }
                    }
                }

                // Recent Notes & Highlights List
                if (uiState.recentNotes.isEmpty() && uiState.recentHighlights.isEmpty()) {
                    item {
                        Card(
                            modifier = Modifier.fillMaxWidth(),
                            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f))
                        ) {
                            Box(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(24.dp),
                                contentAlignment = Alignment.Center
                            ) {
                                Text(
                                    text = "Chưa có ghi chú hoặc đoạn trích nào.\nHãy chọn văn bản khi đọc để lưu giữ tri thức!",
                                    style = MaterialTheme.typography.bodyMedium,
                                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                                    maxLines = 2
                                )
                            }
                        }
                    }
                } else {
                    val combinedList = (uiState.recentNotes + uiState.recentHighlights).take(8)
                    items(combinedList) { item ->
                        HighlightCard(
                            item = item,
                            onClick = {
                                onNavigateToReader(item.book.id, item.highlight.locatorJson)
                            },
                            onToggleReview = {
                                viewModel.toggleReview(item.highlight.id, item.book.id, item.isUnderReview)
                            }
                        )
                    }
                }

                // 5. Recent Bookmarks Section Header
                if (uiState.recentBookmarks.isNotEmpty()) {
                    item {
                        Text(
                            text = "Đánh dấu gần đây",
                            style = MaterialTheme.typography.titleMedium,
                            fontWeight = FontWeight.Bold,
                            modifier = Modifier.padding(top = 8.dp)
                        )
                    }

                    items(uiState.recentBookmarks.take(5)) { item ->
                        BookmarkCard(
                            item = item,
                            onClick = {
                                onNavigateToReader(item.book.id, item.bookmark.locatorJson)
                            }
                        )
                    }
                }

                item { Spacer(modifier = Modifier.height(32.dp)) }
            }
        }
    }
}

@Composable
fun HighlightCard(
    item: HighlightWithBook,
    onClick: () -> Unit,
    onToggleReview: (() -> Unit)? = null
) {
    val highlightColor = when (item.highlight.color.uppercase()) {
        "YELLOW" -> Color(0xFFF9E79F)
        "GREEN" -> Color(0xFFA9DFBF)
        "BLUE" -> Color(0xFFAED6F1)
        "PINK" -> Color(0xFFF5B7B1)
        else -> Color(0xFFF9E79F)
    }

    val chapterTitle = remember(item.highlight.locatorJson) {
        try {
            val obj = org.json.JSONObject(item.highlight.locatorJson)
            obj.optString("title").takeIf { it.isNotBlank() }
        } catch (_: Exception) {
            null
        }
    }

    Card(
        modifier = Modifier
            .fillMaxWidth()
            .clickable(onClick = onClick),
        shape = RoundedCornerShape(14.dp),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f)),
        border = androidx.compose.foundation.BorderStroke(
            1.dp,
            MaterialTheme.colorScheme.outlineVariant.copy(alpha = 0.3f)
        )
    ) {
        Column(modifier = Modifier.padding(14.dp)) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                    modifier = Modifier.weight(1f)
                ) {
                    Box(
                        modifier = Modifier
                            .size(10.dp)
                            .clip(CircleShape)
                            .background(highlightColor)
                    )
                    Text(
                        text = item.book.userTitleOverride ?: item.book.title,
                        style = MaterialTheme.typography.labelMedium,
                        fontWeight = FontWeight.SemiBold,
                        color = MaterialTheme.colorScheme.primary,
                        maxLines = 1,
                        overflow = TextOverflow.Ellipsis
                    )
                    Surface(
                        shape = RoundedCornerShape(4.dp),
                        color = MaterialTheme.colorScheme.secondaryContainer
                    ) {
                        Text(
                            text = item.book.format.name,
                            style = MaterialTheme.typography.labelSmall.copy(fontSize = 10.sp),
                            modifier = Modifier.padding(horizontal = 4.dp, vertical = 2.dp)
                        )
                    }
                    if (chapterTitle != null) {
                        Text(
                            text = "• $chapterTitle",
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                            maxLines = 1,
                            overflow = TextOverflow.Ellipsis
                        )
                    }
                }

                if (onToggleReview != null) IconButton(
                    onClick = onToggleReview,
                    modifier = Modifier.size(48.dp)
                ) {
                    Icon(
                        imageVector = if (item.isUnderReview) Icons.Default.CheckCircle else Icons.Default.Add,
                        contentDescription = localize("Ôn tập"),
                        tint = if (item.isUnderReview) MaterialTheme.colorScheme.tertiary else MaterialTheme.colorScheme.outline,
                        modifier = Modifier.size(20.dp)
                    )
                }
            }

            Spacer(modifier = Modifier.height(8.dp))

            Text(
                text = "“${item.highlight.text.trim()}”",
                style = MaterialTheme.typography.bodyMedium.copy(
                    fontStyle = androidx.compose.ui.text.font.FontStyle.Italic,
                    lineHeight = 22.sp
                ),
                maxLines = 3,
                overflow = TextOverflow.Ellipsis,
                color = MaterialTheme.colorScheme.onSurface
            )

            if (!item.highlight.note.isNullOrBlank()) {
                Spacer(modifier = Modifier.height(10.dp))
                Surface(
                    shape = RoundedCornerShape(8.dp),
                    color = MaterialTheme.colorScheme.surface.copy(alpha = 0.9f),
                    border = androidx.compose.foundation.BorderStroke(
                        1.dp,
                        MaterialTheme.colorScheme.outlineVariant.copy(alpha = 0.4f)
                    ),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Row(
                        modifier = Modifier.padding(10.dp),
                        verticalAlignment = Alignment.Top,
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        Icon(
                            Icons.Default.Edit,
                            contentDescription = null,
                            modifier = Modifier.size(16.dp),
                            tint = MaterialTheme.colorScheme.primary
                        )
                        Text(
                            text = item.highlight.note,
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurface
                        )
                    }
                }
            }
        }
    }
}

@Composable
fun BookmarkCard(
    item: BookmarkWithBook,
    onClick: () -> Unit
) {
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .heightIn(min = 48.dp)
            .clickable(onClick = onClick),
        shape = RoundedCornerShape(12.dp),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.4f)),
        border = androidx.compose.foundation.BorderStroke(
            1.dp,
            MaterialTheme.colorScheme.outlineVariant.copy(alpha = 0.25f)
        )
    ) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(14.dp),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            Icon(AppIcons.Bookmark, contentDescription = null, tint = MaterialTheme.colorScheme.primary)
            Column(modifier = Modifier.weight(1f)) {
                Text(
                    text = item.bookmark.chapterTitle,
                    style = MaterialTheme.typography.bodyMedium,
                    fontWeight = FontWeight.SemiBold,
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis
                )
                if (!item.bookmark.snippet.isNullOrBlank()) {
                    Text(
                        text = item.bookmark.snippet,
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                        maxLines = 1,
                        overflow = TextOverflow.Ellipsis
                    )
                }
                Text(
                    text = item.book.userTitleOverride ?: item.book.title,
                    style = MaterialTheme.typography.labelSmall,
                    color = MaterialTheme.colorScheme.outline
                )
            }
        }
    }
}

@Composable
fun ReviewItemCard(
    itemWithDetails: ReviewItemWithDetails,
    onMarkAsMastered: (String) -> Unit,
    onRemoveFromReview: (String) -> Unit,
    onOpenBook: (String, String?) -> Unit
) {
    val item = itemWithDetails.reviewItem
    val highlight = itemWithDetails.highlight
    val book = itemWithDetails.book
    val now = System.currentTimeMillis()
    val state = ReviewScheduler.memoryState(item, now)

    val highlightColor = when (highlight?.color?.uppercase()) {
        "YELLOW" -> Color(0xFFF9E79F)
        "GREEN" -> Color(0xFFA9DFBF)
        "BLUE" -> Color(0xFFAED6F1)
        "PINK" -> Color(0xFFF5B7B1)
        else -> MaterialTheme.colorScheme.primary
    }

    Card(
        modifier = Modifier
            .fillMaxWidth()
            .clickable {
                if (book != null && highlight != null) {
                    onOpenBook(book.id, highlight.locatorJson)
                }
            },
        shape = RoundedCornerShape(14.dp),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
        border = androidx.compose.foundation.BorderStroke(
            1.dp,
            MaterialTheme.colorScheme.outlineVariant.copy(alpha = 0.35f)
        )
    ) {
        Column(modifier = Modifier.padding(14.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
            // Header: Status badge & review count
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                val (badgeText, badgeBg, badgeTextColor) = when (state) {
                    MemoryState.DUE -> Triple(
                        "Cần ôn lại",
                        MaterialTheme.colorScheme.errorContainer,
                        MaterialTheme.colorScheme.onErrorContainer
                    )
                    MemoryState.MASTERED -> Triple(
                        "Đã nhớ (${item.intervalDays} ngày)",
                        MaterialTheme.colorScheme.secondaryContainer,
                        MaterialTheme.colorScheme.onSecondaryContainer
                    )
                    MemoryState.LEARNING -> Triple(
                        "Đang học (${item.intervalDays} ngày)",
                        MaterialTheme.colorScheme.primaryContainer,
                        MaterialTheme.colorScheme.onPrimaryContainer
                    )
                }

                Surface(
                    shape = RoundedCornerShape(6.dp),
                    color = badgeBg
                ) {
                    Text(
                        text = badgeText,
                        style = MaterialTheme.typography.labelSmall,
                        color = badgeTextColor,
                        fontWeight = FontWeight.Bold,
                        modifier = Modifier.padding(horizontal = 8.dp, vertical = 3.dp)
                    )
                }

                Text(
                    text = "Lần ôn: ${item.reviewCount}",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }

            // Quote text
            if (highlight != null) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    Box(
                        modifier = Modifier
                            .width(3.dp)
                            .height(40.dp)
                            .background(highlightColor, RoundedCornerShape(2.dp))
                    )

                    Column(modifier = Modifier.weight(1f)) {
                        Text(
                            text = "“${highlight.text.trim()}”",
                            style = MaterialTheme.typography.bodyMedium.copy(
                                fontStyle = FontStyle.Italic,
                                lineHeight = 20.sp
                            ),
                            maxLines = 3,
                            overflow = TextOverflow.Ellipsis
                        )

                        if (!highlight.note.isNullOrBlank()) {
                            Spacer(modifier = Modifier.height(6.dp))
                            Surface(
                                shape = RoundedCornerShape(8.dp),
                                color = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f),
                                modifier = Modifier.fillMaxWidth()
                            ) {
                                Row(
                                    modifier = Modifier.padding(8.dp),
                                    verticalAlignment = Alignment.Top,
                                    horizontalArrangement = Arrangement.spacedBy(6.dp)
                                ) {
                                    Icon(
                                        Icons.Default.Edit,
                                        contentDescription = null,
                                        modifier = Modifier.size(14.dp),
                                        tint = MaterialTheme.colorScheme.primary
                                    )
                                    Text(
                                        text = highlight.note,
                                        style = MaterialTheme.typography.bodySmall,
                                        color = MaterialTheme.colorScheme.onSurface
                                    )
                                }
                            }
                        }
                    }
                }
            }

            // Footer: Book title and action buttons
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text(
                    text = book?.userTitleOverride ?: book?.title ?: "Sách không xác định",
                    style = MaterialTheme.typography.labelMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis,
                    modifier = Modifier.weight(1f)
                )

                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(4.dp)
                ) {
                    if (state != MemoryState.MASTERED) {
                        TextButton(
                            onClick = { onMarkAsMastered(item.annotationId) },
                            contentPadding = PaddingValues(horizontal = 8.dp, vertical = 2.dp)
                        ) {
                            Icon(
                                Icons.Default.Check,
                                contentDescription = null,
                                modifier = Modifier.size(16.dp),
                                tint = MaterialTheme.colorScheme.secondary
                            )
                            Spacer(modifier = Modifier.width(4.dp))
                            Text(
                                text = "Đã thuộc",
                                style = MaterialTheme.typography.labelSmall,
                                color = MaterialTheme.colorScheme.secondary
                            )
                        }
                    }

                    IconButton(
                        onClick = { onRemoveFromReview(item.annotationId) },
                        modifier = Modifier.size(32.dp)
                    ) {
                        Icon(
                            Icons.Default.Delete,
                            contentDescription = "Bỏ khỏi ôn tập",
                            modifier = Modifier.size(18.dp),
                            tint = MaterialTheme.colorScheme.outline
                        )
                    }
                }
            }
        }
    }
}
