package com.nocap.app.core.localization

/** English fallback for secondary UI copy that has not needed language-specific wording yet. */
internal object EnglishFallbacks {
    private val values = mapOf(
        "  hoặc  " to "  or  ",
        "Ẩn" to "Hide",
        "Ẩn thanh trạng thái và thanh điều hướng" to "Hide status and navigation bars",
        "Ảnh bìa không được vượt quá 10MB" to "Cover image must not exceed 10 MB",
        "Ảnh bìa:" to "Cover image:",
        "Ảnh đại diện" to "Profile picture",
        "Bạn đã hoàn thành tất cả các thẻ cần ôn tập hôm nay." to "You completed all cards due today.",
        "Bộ sưu tập sẽ bị xóa nhưng các tài liệu bên trong vẫn được giữ nguyên vẹn trong thư viện." to "The collection will be deleted, while its documents remain in the library.",
        "Bộ sưu tập tài liệu" to "Document collections",
        "Cài đặt hiển thị" to "Display settings",
        "Căn đều 2 bên" to "Justified",
        "Căn lề" to "Alignment",
        "Căn trái" to "Align left",
        "Chia sẻ trích dẫn" to "Share quote",
        "Chỉnh sửa đoạn tô sáng" to "Edit highlight",
        "Chọn ảnh mới" to "Choose new image",
        "Chọn màu tô sáng:" to "Choose highlight color:",
        "Chọn màu:" to "Choose color:",
        "Chưa có bộ sưu tập nào. Hãy tạo bộ sưu tập mới trước." to "No collections yet. Create one first.",
        "Chưa có đủ dữ liệu phiên đọc (các phiên đọc hợp lệ từ 5 giây trở lên sẽ được ghi nhận tự động)." to "There is not enough reading-session data yet. Sessions lasting at least 5 seconds are recorded automatically.",
        "Chưa có tài liệu nào gắn thẻ này." to "No documents use this tag yet.",
        "Chưa có tài liệu nào trong bộ sưu tập này." to "This collection has no documents yet.",
        "Chưa có thẻ nào. Hãy tạo thẻ trong tab Thẻ trước." to "No tags yet. Create one in the Tags tab first.",
        "Chưa có thẻ nào. Nhập tên ở trên để tạo thẻ mới." to "No tags yet. Enter a name above to create one.",
        "Chúc bạn đọc sách vui vẻ \uD83D\uDCDA" to "Enjoy your reading 📚",
        "Chuyển vào Chưa phân loại" to "Move to Unsorted",
        "Đã bỏ ghim tài liệu" to "Document unpinned",
        "Đã cập nhật ảnh bìa tùy chỉnh" to "Custom cover updated",
        "Đã cập nhật bộ sưu tập" to "Collection updated",
        "Đã cập nhật thẻ cho tài liệu" to "Document tags updated",
        "Đã cập nhật thông tin tài liệu" to "Document details updated",
        "Đã chuyển vào Chưa phân loại" to "Moved to Unsorted",
        "Đã có tài khoản? Đăng nhập ngay" to "Already have an account? Sign in",
        "Đã đổi tên thẻ" to "Tag renamed",
        "Đã ghim" to "Pinned",
        "Đã ghim tài liệu" to "Document pinned",
        "Đã gửi email khôi phục mật khẩu. Vui lòng kiểm tra hộp thư!" to "Password recovery email sent. Check your inbox.",
        "Đã gửi lại email xác thực. Vui lòng kiểm tra hộp thư!" to "Verification email sent again. Check your inbox.",
        "Đã hoàn thành tổ chức" to "Organization completed",
        "Đã hủy tải tài liệu" to "Download cancelled",
        "Đã khôi phục tài liệu" to "Document restored",
        "Đã lưu trữ tài liệu" to "Document archived",
        "Đã xóa ảnh bìa tùy chỉnh" to "Custom cover removed",
        "Đã xóa bộ sưu tập" to "Collection deleted",
        "Đã xóa khỏi bộ sưu tập" to "Removed from collection",
        "Đã xóa tài liệu khỏi thư viện" to "Document removed from library",
        "Đã xóa thẻ" to "Tag deleted",
        "Đang áp dụng cài đặt riêng" to "Using book-specific settings",
        "Đăng ký thất bại" to "Account creation failed",
        "Đăng nhập Google thất bại" to "Google sign-in failed",
        "Đăng nhập thất bại" to "Sign-in failed",
        "Đang ôn tập" to "Reviewing",
        "Đang tìm kiếm..." to "Searching…",
        "Đánh dấu" to "Bookmark",
        "Đánh dấu & ghi chú" to "Bookmarks and notes",
        "Đánh dấu đã tổ chức" to "Mark as organized",
        "Đánh dấu gần đây" to "Recent bookmarks",
        "Đánh dấu hoàn thành" to "Mark complete",
        "Đánh dấu: Chưa đọc" to "Mark as not started",
        "Đánh dấu: Đang đọc" to "Mark as reading",
        "Đánh dấu: Hoàn thành" to "Mark as completed",
        "Đặt lại về mặc định chung" to "Reset to app defaults",
        "Độ sáng theo hệ thống" to "System brightness",
        "Độ sáng tùy chỉnh: " to "Custom brightness: ",
        "Đoạn trích" to "Highlights",
        "Dọc" to "Portrait",
        "Đọc bản hiện tại" to "Read current version",
        "Đổi tên bộ sưu tập" to "Rename collection",
        "Đổi tên thẻ" to "Rename tag",
        "Đóng chọn" to "Exit selection",
        "Dùng Volume Up/Down để chuyển trang" to "Use Volume Up/Down to turn pages",
        "Gắn thẻ hàng loạt" to "Add tags in bulk",
        "Gắn thẻ tài liệu" to "Tag document",
        "Gắn thẻ tài liệu để tìm kiếm đa chiều và phân loại kiến thức theo chủ đề." to "Tag documents to find and organize knowledge by topic.",
        "Ghi chú của bạn:" to "Your note:",
        "Ghim tài liệu" to "Pin document",
        "Giao diện" to "Appearance",
        "Giới thiệu" to "About",
        "Gửi liên kết đặt lại mật khẩu" to "Send password reset link",
        "Hãy quay lại thư viện và mở lại. Nếu vẫn gặp lỗi, thử nhập lại tệp gốc. Tài liệu và ghi chú của bạn vẫn được giữ." to "Return to the library and open it again. If the problem continues, reimport the original file. Your documents and notes remain safe.",
        "Hệ thống hỗ trợ tìm kiếm không dấu (VD: 'tri tue' tìm được 'Trí Tuệ'). Vui lòng thử từ khóa khác." to "Search ignores Vietnamese accents. Try another keyword.",
        "Hiện" to "Show",
        "Hiển thị đồng hồ thời gian" to "Show clock",
        "Hiển thị phần trăm (%)" to "Show percentage (%)",
        "Hiển thị tên chương / tiến độ" to "Show chapter name or progress",
        "Kế thừa cài đặt chung toàn ứng dụng" to "Use app-wide settings",
        "Khóa hướng màn hình" to "Lock screen orientation",
        "Khôi phục bìa gốc" to "Restore original cover",
        "Không thể cập nhật tên hiển thị trên máy chủ" to "Unable to update the display name on the server",
        "Không thể gửi email khôi phục" to "Unable to send recovery email",
        "Không thể gửi email xác thực" to "Unable to send verification email",
        "Không thể kết nối tài khoản Google" to "Unable to connect to Google",
        "Không thể làm mới trạng thái" to "Unable to refresh status",
        "Không thể mở tệp CBZ" to "Unable to open CBZ file",
        "Không thể xóa tài khoản" to "Unable to delete account",
        "Không thể xóa tài liệu" to "Unable to delete document",
        "Không tìm thấy thông tin sách" to "Book details not found",
        "Kiểm tra kết nối để xem danh mục. Bạn vẫn có thể vào Tài liệu để thêm tệp hoặc đọc thư viện trên máy." to "Check your connection to view the catalog. You can still add documents and read your offline library.",
        "Lọc trong ghi chú..." to "Filter notes…",
        "Lỗi đổi tên" to "Rename failed",
        "Lỗi đổi tên thẻ" to "Unable to rename tag",
        "Lỗi gắn thẻ" to "Unable to update tags",
        "Lỗi mở sách: " to "Unable to open book: ",
        "Lỗi tải tệp CBZ" to "Unable to load CBZ file",
        "Lỗi tạo bộ sưu tập" to "Unable to create collection",
        "Lỗi tạo thẻ" to "Unable to create tag",
        "Lưu trích dẫn" to "Save quote",
        "Lưu trữ tài liệu" to "Archive document",
        "Mật khẩu phải có ít nhất 12 ký tự" to "Password must contain at least 12 characters",
        "Mật khẩu xác nhận không khớp" to "Passwords do not match",
        "Mọi định dạng" to "All formats",
        "Người dùng NoCap" to "NoCap user",
        "Nhập email tài khoản của bạn để nhận liên kết đặt lại mật khẩu." to "Enter your account email to receive a password reset link.",
        "Nhập nội dung ghi chú..." to "Enter a note…",
        "Nhập tên bộ sưu tập:" to "Enter collection name:",
        "Nhập tên thẻ (tự động chuẩn hóa chữ thường):" to "Enter a tag name (automatically normalized to lowercase):",
        "Nhập từ khóa tìm kiếm..." to "Enter search keywords…",
        "Phông chữ" to "Fonts",
        "Quay lại Bộ nhớ đọc" to "Back to Reading Memory",
        "Sách chưa được tải về máy." to "This book has not been downloaded.",
        "Sách điện tử" to "Ebook",
        "Sửa thông tin tài liệu" to "Edit document details",
        "Tác giả hiển thị:" to "Displayed author:",
        "Tài khoản đã được xóa thành công" to "Account deleted successfully",
        "Tài khoản Google" to "Google account",
        "Tài liệu mới nhập sẽ ở đây. Nhấn \"Hoàn thành\" khi bạn đã phân loại xong." to "Newly imported documents appear here. Tap “Complete” after organizing them.",
        "Tài liệu PDF này ở dạng scan hoặc ảnh và không chứa lớp văn bản số. NoCap tôn trọng tính nguyên bản của tài liệu và không giả lập nhận dạng ký tự (OCR)." to "This PDF is a scan or image without a selectable text layer. NoCap preserves the original document and does not simulate OCR.",
        "Tải sách" to "Download book",
        "Tạo bộ sưu tập để phân loại và sắp xếp tài liệu của bạn gọn gàng hơn." to "Create collections to keep your documents organized.",
        "Tạo bộ sưu tập mới" to "Create collection",
        "Tạo tài khoản thành công! Vui lòng kiểm tra email để xác thực." to "Account created. Check your email to verify it.",
        "Tạo thẻ mới" to "Create tag",
        "Tệp ảnh không hợp lệ" to "Invalid image file",
        "Tệp sách không tồn tại hoặc đã bị xóa khỏi thiết bị." to "The book file is missing or was removed from this device.",
        "Thao tác thất bại" to "Action failed",
        "Thẻ sẽ bị xóa khỏi hệ thống nhưng tất cả tài liệu vẫn được giữ nguyên vẹn trong thư viện." to "The tag will be deleted, while all documents remain in the library.",
        "Thêm phông (.ttf/.otf)" to "Add font (.ttf/.otf)",
        "Thêm vào bộ sưu tập hàng loạt" to "Add to collections in bulk",
        "Thêm vào ôn tập hàng ngày" to "Add to daily review",
        "Thử từ khóa hoặc thể loại khác" to "Try another keyword or category",
        "Tiêu đề hiển thị:" to "Displayed title:",
        "Tìm tên, tác giả, thẻ, bộ sưu tập..." to "Search names, authors, tags, or collections…",
        "Tìm trong tài liệu và ghi chú" to "Search documents and notes",
        "Tô sáng màu hồng" to "Pink highlight",
        "Tô sáng màu vàng" to "Yellow highlight",
        "Tô sáng màu xanh dương" to "Blue highlight",
        "Tô sáng màu xanh lá" to "Green highlight",
        "Trả phí" to "Paid",
        "Trang trước" to "Previous page",
        "Trích dẫn NoCap" to "NoCap quote",
        "Trích đoạn & Ghi chú" to "Highlights and notes",
        "Trích xuất văn bản" to "Extract text",
        "Tùy chỉnh riêng cho sách này" to "Use custom settings for this book",
        "Văn bản trích dẫn:" to "Quoted text:",
        "Về thư viện" to "Back to library",
        "Xóa bản tải" to "Remove download",
        "Xóa bộ sưu tập" to "Delete collection",
        "Xóa bộ sưu tập: " to "Delete collection: ",
        "Xóa khỏi bộ sưu tập" to "Remove from collection",
        "Xóa tài liệu khỏi thư viện?" to "Remove document from library?",
        "Xóa thẻ" to "Delete tag",
        "Xóa tìm kiếm" to "Clear search",
        "Xuất sắc!" to "Excellent!"
    )

    operator fun get(source: String): String? = values[source]
}
