package com.ebookreader.app.core.designsystem

import androidx.compose.ui.graphics.Color

// Light Colors
val LightPrimary = Color(0xFF1E3A8A)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDBEAFE)
val LightOnPrimaryContainer = Color(0xFF1E40AF)
val LightSecondary = Color(0xFF0D9488)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightBackground = Color(0xFFF8FAFC)
val LightOnBackground = Color(0xFF0F172A)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF0F172A)
val LightSurfaceVariant = Color(0xFFF1F5F9)
val LightOnSurfaceVariant = Color(0xFF475569)

// Dark Colors
val DarkPrimary = Color(0xFF93C5FD)
val DarkOnPrimary = Color(0xFF1E3A8A)
val DarkPrimaryContainer = Color(0xFF1E40AF)
val DarkOnPrimaryContainer = Color(0xFFDBEAFE)
val DarkSecondary = Color(0xFF2DD4BF)
val DarkOnSecondary = Color(0xFF134E4A)
val DarkBackground = Color(0xFF0F172A)
val DarkOnBackground = Color(0xFFF8FAFC)
val DarkSurface = Color(0xFF1E293B)
val DarkOnSurface = Color(0xFFF8FAFC)
val DarkSurfaceVariant = Color(0xFF334155)
val DarkOnSurfaceVariant = Color(0xFF94A3B8)

// Sepia Colors (Warm reading palette)
val SepiaBackground = Color(0xFFFBF0D9)
val SepiaOnBackground = Color(0xFF3D3226)
val SepiaSurface = Color(0xFFF4E5C7)
val SepiaOnSurface = Color(0xFF3D3226)
val SepiaPrimary = Color(0xFF8C531B)
val SepiaOnPrimary = Color(0xFFFFFFFF)
val SepiaPrimaryContainer = Color(0xFFEBD3B0)
val SepiaOnPrimaryContainer = Color(0xFF5C330B)
val SepiaSecondary = Color(0xFF705D49)
val SepiaOnSecondary = Color(0xFFFFFFFF)
val SepiaSurfaceVariant = Color(0xFFEADBBE)
val SepiaOnSurfaceVariant = Color(0xFF5C4E3D)
