package com.nocap.app.core.designsystem

import androidx.compose.ui.graphics.Color

// Light Colors
val LightPrimary = Color(0xFF1E3A8A)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDBEAFE)
val LightOnPrimaryContainer = Color(0xFF1E40AF)
val LightSecondary = Color(0xFF0D9488)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightBackground = Color(0xFFF8FAFC)
val LightOnBackground = Color(0xFF0F172A)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF0F172A)
val LightSurfaceVariant = Color(0xFFF1F5F9)
val LightOnSurfaceVariant = Color(0xFF475569)

// Dark Colors
val DarkPrimary = Color(0xFF93C5FD)
val DarkOnPrimary = Color(0xFF1E3A8A)
val DarkPrimaryContainer = Color(0xFF1E40AF)
val DarkOnPrimaryContainer = Color(0xFFDBEAFE)
val DarkSecondary = Color(0xFF2DD4BF)
val DarkOnSecondary = Color(0xFF134E4A)
val DarkBackground = Color(0xFF0F172A)
val DarkOnBackground = Color(0xFFF8FAFC)
val DarkSurface = Color(0xFF1E293B)
val DarkOnSurface = Color(0xFFF8FAFC)
val DarkSurfaceVariant = Color(0xFF334155)
val DarkOnSurfaceVariant = Color(0xFFA0AEC0)

// Sage Colors (calm, low-distraction application palette)
val SageLightPrimary = Color(0xFF2F6B57)
val SageLightOnPrimary = Color(0xFFFFFFFF)
val SageLightPrimaryContainer = Color(0xFFB7F0D2)
val SageLightOnPrimaryContainer = Color(0xFF0B3B2D)
val SageLightSecondary = Color(0xFF53665C)
val SageLightOnSecondary = Color(0xFFFFFFFF)
val SageLightBackground = Color(0xFFF7FAF8)
val SageLightOnBackground = Color(0xFF15201A)
val SageLightSurface = Color(0xFFFFFFFF)
val SageLightOnSurface = Color(0xFF15201A)
val SageLightSurfaceVariant = Color(0xFFE2EBE5)
val SageLightOnSurfaceVariant = Color(0xFF405149)

val SageDarkPrimary = Color(0xFF9AD5BC)
val SageDarkOnPrimary = Color(0xFF073B2B)
val SageDarkPrimaryContainer = Color(0xFF1B513F)
val SageDarkOnPrimaryContainer = Color(0xFFB7F0D2)
val SageDarkSecondary = Color(0xFFB7CCBF)
val SageDarkOnSecondary = Color(0xFF23372D)
val SageDarkBackground = Color(0xFF0F1714)
val SageDarkOnBackground = Color(0xFFF2FBF5)
val SageDarkSurface = Color(0xFF18231E)
val SageDarkOnSurface = Color(0xFFF2FBF5)
val SageDarkSurfaceVariant = Color(0xFF31443A)
val SageDarkOnSurfaceVariant = Color(0xFFB8CCC0)

// Violet Colors (knowledge and creative-focus application palette)
val VioletLightPrimary = Color(0xFF6750A4)
val VioletLightOnPrimary = Color(0xFFFFFFFF)
val VioletLightPrimaryContainer = Color(0xFFEADDFF)
val VioletLightOnPrimaryContainer = Color(0xFF21005D)
val VioletLightSecondary = Color(0xFF625B71)
val VioletLightOnSecondary = Color(0xFFFFFFFF)
val VioletLightBackground = Color(0xFFFFFBFE)
val VioletLightOnBackground = Color(0xFF1D1B20)
val VioletLightSurface = Color(0xFFFFFBFE)
val VioletLightOnSurface = Color(0xFF1D1B20)
val VioletLightSurfaceVariant = Color(0xFFE7E0EC)
val VioletLightOnSurfaceVariant = Color(0xFF49454F)

val VioletDarkPrimary = Color(0xFFD0BCFF)
val VioletDarkOnPrimary = Color(0xFF381E72)
val VioletDarkPrimaryContainer = Color(0xFF4F378B)
val VioletDarkOnPrimaryContainer = Color(0xFFEADDFF)
val VioletDarkSecondary = Color(0xFFCCC2DC)
val VioletDarkOnSecondary = Color(0xFF332D41)
val VioletDarkBackground = Color(0xFF141218)
val VioletDarkOnBackground = Color(0xFFE6E0E9)
val VioletDarkSurface = Color(0xFF211F26)
val VioletDarkOnSurface = Color(0xFFE6E0E9)
val VioletDarkSurfaceVariant = Color(0xFF49454F)
val VioletDarkOnSurfaceVariant = Color(0xFFCAC4D0)

// Sepia Colors (Warm reading palette)
val SepiaBackground = Color(0xFFFBF0D9)
val SepiaOnBackground = Color(0xFF3D3226)
val SepiaSurface = Color(0xFFF4E5C7)
val SepiaOnSurface = Color(0xFF3D3226)
val SepiaPrimary = Color(0xFF8C531B)
val SepiaOnPrimary = Color(0xFFFFFFFF)
val SepiaPrimaryContainer = Color(0xFFEBD3B0)
val SepiaOnPrimaryContainer = Color(0xFF5C330B)
val SepiaSecondary = Color(0xFF705D49)
val SepiaOnSecondary = Color(0xFFFFFFFF)
val SepiaSurfaceVariant = Color(0xFFEADBBE)
val SepiaOnSurfaceVariant = Color(0xFF5C4E3D)
